// Code generated by MockGen. DO NOT EDIT.
// Source: /home/roma/roma/LoudyBack/internal/services/artists/init.go
//
// Generated by this command:
//
//	mockgen -source=/home/roma/roma/LoudyBack/internal/services/artists/init.go -destination=/home/roma/roma/LoudyBack/internal/services/artists/mocks/mockgen.go
//

// Package mock_artists is a generated GoMock package.
package mock_artists

import (
	context "context"
	models "loudy-back/internal/domain/models/artists"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockArtistsProvider is a mock of ArtistsProvider interface.
type MockArtistsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockArtistsProviderMockRecorder
	isgomock struct{}
}

// MockArtistsProviderMockRecorder is the mock recorder for MockArtistsProvider.
type MockArtistsProviderMockRecorder struct {
	mock *MockArtistsProvider
}

// NewMockArtistsProvider creates a new mock instance.
func NewMockArtistsProvider(ctrl *gomock.Controller) *MockArtistsProvider {
	mock := &MockArtistsProvider{ctrl: ctrl}
	mock.recorder = &MockArtistsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArtistsProvider) EXPECT() *MockArtistsProviderMockRecorder {
	return m.recorder
}

// Artist mocks base method.
func (m *MockArtistsProvider) Artist(ctx context.Context, name string) (models.Artist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Artist", ctx, name)
	ret0, _ := ret[0].(models.Artist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Artist indicates an expected call of Artist.
func (mr *MockArtistsProviderMockRecorder) Artist(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Artist", reflect.TypeOf((*MockArtistsProvider)(nil).Artist), ctx, name)
}

// MockArtistsCreator is a mock of ArtistsCreator interface.
type MockArtistsCreator struct {
	ctrl     *gomock.Controller
	recorder *MockArtistsCreatorMockRecorder
	isgomock struct{}
}

// MockArtistsCreatorMockRecorder is the mock recorder for MockArtistsCreator.
type MockArtistsCreatorMockRecorder struct {
	mock *MockArtistsCreator
}

// NewMockArtistsCreator creates a new mock instance.
func NewMockArtistsCreator(ctrl *gomock.Controller) *MockArtistsCreator {
	mock := &MockArtistsCreator{ctrl: ctrl}
	mock.recorder = &MockArtistsCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArtistsCreator) EXPECT() *MockArtistsCreatorMockRecorder {
	return m.recorder
}

// CreateArtist mocks base method.
func (m *MockArtistsCreator) CreateArtist(ctx context.Context, name, cover, bio string) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArtist", ctx, name, cover, bio)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArtist indicates an expected call of CreateArtist.
func (mr *MockArtistsCreatorMockRecorder) CreateArtist(ctx, name, cover, bio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArtist", reflect.TypeOf((*MockArtistsCreator)(nil).CreateArtist), ctx, name, cover, bio)
}
