env: "local"

token_ttl: 24h
grpc:
  auth:
    port: 44000
    timeout: 10h
  artists:
    port: 44001
    timeout: 10h
clients:
  auth:
    timeout: "4s"
    retriesCount: 5
    insecure: true
  artists:
    timeout: "4s"
    retriesCount: 5
    insecure: true
