env: "local"

token_ttl: 24h
grpc:
  auth:
    port: 44000
    timeout: 10h
  artists:
    port: 44001
    timeout: 10h
  albums:
    port: 44002
    timeout: 10h
  profiles:
    port: 44003
    timeout: 10h
  tracks:
    port: 44003
    timeout: 10h
clients:
  auth:
    timeout: "4s"
    retriesCount: 5
    insecure: true
  artists:
    timeout: "4s"
    retriesCount: 5
    insecure: true
  albums:
    timeout: "4s"
    retriesCount: 5
    insecure: true
  profiles:
    timeout: "4s"
    retriesCount: 5
    insecure: true
  tracks:
    timeout: "4s"
    retriesCount: 5
    insecure: true
